{% set name = "cloudpathlib" %}
{% set version = "0.21.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb8f6b890a3d37b35f0eabff86721bb8d35dfc6a6be98c1f4d34b19e989c6641

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - wheel
  run:
    - python

outputs:
  - name: {{ name }}
    requirements:
      host:
        - pip
        - python
        - setuptools
        - flit-core >=3.2,<4
      run:
        - python
        - typing_extensions >4  # [py<311]
    test:
      imports:
        - {{ name }}
      requires:
        - pip
      commands:
        - pip check
        # Cannot run tests with pytest since they're not included in the source tar.

  - name: cloudpathlib-azure
    requirements:
      host:
        - python
        - setuptools
      run:
        - python
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - azure-storage-blob >=12
        - azure-storage-file-datalake >=12
    test:
      imports:
        - cloudpathlib
      requires:
        - pip
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['azure'].validate_completeness()"

  - name: cloudpathlib-gs
    requirements:
      host:
        - python
        - setuptools
      run:
        - python
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - google-cloud-storage
    test:
      imports:
        - cloudpathlib
      requires:
        - pip
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['gs'].validate_completeness()"

  - name: cloudpathlib-s3
    requirements:
      host:
        - python
        - setuptools
      run:
        - python
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - boto3 >=1.34.0
    test:
      imports:
        - cloudpathlib
      requires:
        - pip
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['s3'].validate_completeness()"

  - name: cloudpathlib-all
    requirements:
      host:
        - python
        - setuptools
      run:
        - python
        - {{ pin_subpackage('cloudpathlib-azure', exact=True) }}
        - {{ pin_subpackage('cloudpathlib-gs', exact=True) }}
        - {{ pin_subpackage('cloudpathlib-s3', exact=True) }}
    test:
      imports:
        - cloudpathlib
      requires:
        - pip
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['azure'].validate_completeness()"
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['gs'].validate_completeness()"
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['s3'].validate_completeness()"

about:
  home: https://github.com/drivendataorg/cloudpathlib
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: pathlib.Path-style classes for interacting with files in different cloud storage services.
  description: |
    A Python library with classes that mimic pathlib.Path's interface for URIs from different cloud storage services.
  doc_url: https://cloudpathlib.drivendata.org/
  dev_url: https://github.com/drivendataorg/cloudpathlib

extra:
  skip-lints:
    - outputs_not_unique
  recipe-maintainers:
    - jayqi
