{% set name = "cloudpathlib" %}
{% set version = "0.16.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cdfcd35d46d529587d744154a0bdf962aca953b725c8784cd2ec478354ea63a3

build:
  number: 1
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - flit-core >=3.2,<4
  run:
    - python
    - importlib-metadata    # [py<38]
    - typing_extensions >4  # [py<311]

test:
  imports:
    - cloudpathlib
  requires:
    - pip
  commands:
    - pip check

outputs:
  - name: cloudpathlib

  - name: cloudpathlib-azure
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - azure-storage-blob >=12
    test:
      imports:
        - cloudpathlib
      requires:
        - pip
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['azure'].validate_completeness()"

  - name: cloudpathlib-gs
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - google-cloud-storage
    test:
      imports:
        - cloudpathlib
      requires:
        - pip
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['gs'].validate_completeness()"

  - name: cloudpathlib-s3
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('cloudpathlib', exact=True) }}
        - boto3
    test:
      imports:
        - cloudpathlib
      requires:
        - pip
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['s3'].validate_completeness()"

  - name: cloudpathlib-all
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('cloudpathlib-azure', exact=True) }}
        - {{ pin_subpackage('cloudpathlib-gs', exact=True) }}
        - {{ pin_subpackage('cloudpathlib-s3', exact=True) }}
    test:
      imports:
        - cloudpathlib
      requires:
        - pip
      commands:
        - pip check
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['azure'].validate_completeness()"
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['gs'].validate_completeness()"
        - python -c "from cloudpathlib.cloudpath import implementation_registry; implementation_registry['s3'].validate_completeness()"

about:
  home: https://github.com/drivendataorg/cloudpathlib
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: pathlib.Path-style classes for interacting with files in different cloud storage services.
  description: |
    A Python library with classes that mimic pathlib.Path's interface for URIs from different cloud storage services.
  doc_url: https://cloudpathlib.drivendata.org/
  dev_url: https://github.com/drivendataorg/cloudpathlib

extra:
  recipe-maintainers:
    - jayqi
